### ISSUE TITLE
FutureWarning for pandas.lib deprecation 

### ISSUE THREAD

**Issue by Winterflower** [nicolasmiller/pyculiarity#16]
On pyculiarity import, pandas displays the following warning:

`detect_vec.py:6: FutureWarning: The pandas.lib module is deprecated and will be removed in a future version. These are private functions and can be accessed from pandas._libs.lib instead
  from pandas.lib import Timestamp`

**Comment by nicolasmiller** [comment]
Fixed in https://github.com/nicolasmiller/pyculiarity/pull/19
