### ISSUE TITLE
r.py doesn't support python 2 any more

### ISSUE THREAD

**Issue by rotten** [nicolasmiller/pyculiarity#20]
```
Collecting rpy2 (from pyculiarity)
  Downloading rpy2-2.9.1.tar.gz (192kB)
    100% |████████████████████████████████| 194kB 6.6MB/s 
    Complete output from command python setup.py egg_info:
    rpy2 is no longer supporting Python < 3. Consider using an older rpy2 release when using an older Python release.
```

This, combined with the pandas deprecation warnings (mentioned in another issue and pull request), means that unless pyculiarity can be bumped to python 3 pretty soon, it will, sadly, become unusable.  It was a handy little library and we'll miss it.

Are there any plans to support Python 3, or should we be looking for a new tool to do this sort of thing?

**Comment by nicolasmiller** [comment]
I haven't had a chance to play with this library for some time and am not actively using it. I'd like to preserve compatibility with both Python 2 and 3 if possible. The issues you mention seem pretty trivial to fix. Forcing an explicit dependency on a previous version of rpy2 resolves that part. If you take a look at my latest commit, I've nearly got all the tests passing on both 2 and 3. There's one still failing on 3. Perhaps you can take a look and submit a PR?

**Comment by zrnsm** [comment]
Using a python native STL implementation now. Closing.
