### ISSUE TITLE
Updating the PyPI package?

### ISSUE THREAD

**Issue by michael-erasmus** [nicolasmiller/pyculiarity#22]
Hi @nicolasmiller!

I was curious if the [PyPI package](https://pypi.org/project/pyculiarity/) could be updated to the latest version of the project? It seems at the moment the package hasn't been updated since July 23, 2015. 

This will make it easier to just do a `pip install pyculiarity` instead of having to install from github.

**Comment by michael-erasmus** [comment]
I think this also leads to people still running into and reporting errors that have been fixed, like here: https://github.com/nicolasmiller/pyculiarity/issues/3#issuecomment-381847836

**Comment by quindici** [comment]
+1 on this

**Comment by zrnsm** [comment]
PyPI updated with latest merged PRs.
