### ISSUE TITLE
Use a Python STL instead of R

### ISSUE THREAD

**Issue by JoshuaC3** [nicolasmiller/pyculiarity#23]
See https://github.com/jrmontag/STLDecompose

**Comment by nicolasmiller** [comment]
Cool. It looks like this implementation is based on the one from statsmodels which I've tried in the past. At the time it was giving me results that I wasn't happy with. I'd love to see the R dependency removed if we can show that an alternative implementation of STL is equivalent. Happy to review a pull request.

**Comment by JoshuaC3** [comment]
Will take a look into this and see if I'm up to it. Will report back.

**Comment by zrnsm** [comment]
Latest version now uses a python native STL.
